# Generated by Django 5.0 on 2023-12-08 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Job',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_title', models.CharField(max_length=255)),
                ('location', models.CharField(max_length=255)),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('job_position', models.CharField(choices=[('DevOps', 'DevOps'), ('Software Engineer', 'Software Engineer'), ('Project Manager', 'Project Manager')], max_length=50)),
                ('job_description', models.TextField()),
                ('job_tools', models.TextField()),
                ('job_image', models.ImageField(blank=True, null=True, upload_to='job_images/')),
            ],
        ),
    ]
