# Generated by Django 5.0 on 2023-12-10 18:39

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0002_alter_job_job_image_alter_job_job_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='job',
            name='job_position',
            field=models.CharField(choices=[('DevOps', 'DevOps'), ('Software Engineer', 'Software Engineer'), ('Project Manager', 'Project Manager'), ('SSr. ServiceNow Monitoring Integration', 'SSr. ServiceNow Monitoring Integration'), ('Jr. CEM Arch & Infrastructure Analyst', 'Jr. CEM Arch & Infrastructure Analyst'), ('Jr. CEM Operations', 'Jr. CEM Operatios')], max_length=200),
        ),
    ]
