# Generated by Django 5.0 on 2023-12-10 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('curriculum', '0005_remove_job_job_id_job_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='job_salvame',
            field=models.TextField(default='salvame'),
            preserve_default=False,
        ),
    ]
